apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 907518122181.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newName: 907518122181.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
